# Generated by Django 3.0.6 on 2020-05-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_auto_20200522_1650'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='computer',
            managers=[
            ],
        ),
    ]
