# Generated by Django 3.0.6 on 2020-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_auto_20200523_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, upload_to='computer/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='computer',
            name='type',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
