# Generated by Django 3.0.6 on 2020-05-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_auto_20200524_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='type',
            new_name='tip',
        ),
    ]
