# Generated by Django 3.0.6 on 2020-05-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0006_auto_20200524_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, height_field=100, upload_to='computer/%Y/%m/%d', width_field=100),
        ),
    ]
